kdeclarative: Add include of QDebug for kpackagelauncherqml
The GCC triggers a build error as:

| .../src/kpackagelauncherqml/main.cpp: In function 'int main(int, char**)':
| .../src/kpackagelauncherqml/main.cpp:70:18: error: invalid use of incomplete type 'class QDebug'
|          qWarning() << "The specified Application package is not valid.";

Fix this adding the missing include of QDebug header file.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>