avogadrolibs: specify SRCREV_FORMAT
The avogadrolibs.inc specifies three source repos in its SRC_URI, but
does not use SRCREV_FORMAT to declare which is the primary source. As of
nanbield, this causes a parse-time error.

```
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.
```

Assert a valid SRCREV_FORMAT, to avoid this error.

Signed-off-by: Alex Stewart <alex.stewart@ni.com>