exiv2: Fix link failure caused by lost dependency on libpthread
0001-CMakeLists.txt-do-not-find-system-thread-library-it-.patch caused the following link error.

| CMakeFiles/Makefile2:277: recipe for target 'src/CMakeFiles/exiv2.dir/all' failed
| make[1]: *** [src/CMakeFiles/exiv2.dir/all] Error 2
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_unlock'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_init'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_rdlock'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_destroy'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_wrlock'

These link error caused by lost dependency on libpthread.
This patch disables the TRY_RUN call in the -pthread test to avoid the original error.
With this change, 0001-CMakeLists.txt-do-not-find-system-thread-library-it-.patch can be deleted.

Signed-off-by: wata2ki <wata2ki@gmail.com>