Re-introduce lmdb meta-oe's version causes nothing but trouble
Yeah should go fixing it but haven't got the time...

Error seen:
ERROR: baloo-5.86.0-r0 do_package: baloo: Multiple shlib providers for liblmdb.so.0.9.29: lmdb, lmdb (used by files: /home/superandy/tmp/oe-core-glibc/work/cortexa72-mortsgna-linux/baloo/5.86.0-r0/packages-split/baloo/usr/lib/libKF5BalooEngine.so.5.86.0)

This reverts commit 6443b5b88bf7ca69ee8951aa608a95b68d3541da.